routes/web.php
<?php
Route::get('/', 'HomeController@home')->name('home');

$client_route = false;
foreach (\App\Models\Countries::all() as $country) {
    $path = explode('/', \Request::path());
    if (strtolower(str_replace(' ', '-', $country->country_name)) === $path[0]) {
        $client_route = true;
    }
}

if (auth()->check() || auth()->guard('dealer')->check()) {
    return redirect('/admin');
} else {
    if ($client_route) {
        /* ----- Switch Language ----- */
        Route::get('{country_name}/set/lang/en', 'HomeController@setLangEn');
        Route::get('{country_name}/set/lang/local', 'HomeController@setLangLocal');
        
        /* ----- Countries ----- */
        Route::get('/{country_name}', 'HomeController@home');
        Route::get('/{country_name}/news', 'HomeController@news')->name('news');
        Route::get('/{country_name}/news/{id}', 'HomeController@news_detail')->name('news_detail');
        Route::get('/{country_name}/boat/{boat_model}', 'HomeController@boat_detail');
        Route::get('/{country_name}/about-malibu', 'HomeController@only_malibu')->name('about-malibu');
        Route::get('/{country_name}/find-a-dealer', 'HomeController@find_dealer')->name('find-dealer');
        Route::get('/{country_name}/contact-dealer', 'HomeController@contact_dealer')->name('contact-dealer');
        Route::get('/{country_name}/all-boats', 'HomeController@all_boats')->name('all-boats');
        Route::get('/{country_name}/inventory', 'HomeController@inventory')->name('inventory');
        Route::get('/{country_name}/inventory/{id}', 'HomeController@inventory_detail')->name('inventory_detail');
    }
    
    /* ----- Login for admin or dealer ----- */
    Route::get('admin', 'BackEndController@login')->name('login');
    Route::post('login', 'BackEndController@post_login')->name('post.login');
    
    /* ----- Contact Dealer ----- */
    Route::post('/session/contact-dealer/store', 'HomeController@session_contact_dealer_store')->name('session.contact-dealer.store');
    
    /* ----- TinyMCE ----- */
    Route::post('tinymce/news/upload', 'TinyMCEController@post_news_upload');
    
    /* ----- Send Mail ----- */
    Route::prefix('mail/send')->group(function () {
        Route::post('contact-us', 'SendMailController@postContactUs')->name('mail.send.contact-us');
        Route::prefix('contact-dealer')->group(function () {
            Route::post('free-test-drive', 'SendMailController@postContactDealerFreeTestDrive')->name('mail.send.contact-dealer.free-test-drive');
            Route::post('request-catalog', 'SendMailController@postContactDealerRequestCatalog')->name('mail.send.contact-dealer.request-catalog');
            Route::post('general', 'SendMailController@postContactDealerGeneral')->name('mail.send.contact-dealer.general');
            Route::post('inventory', 'SendMailController@postContactDealerInventory')->name('mail.send.contact-dealer.inventory');
        });
    });
    
    /* ----- API ----- */
    Route::prefix('api')->group(function () {
        Route::post('set/home_active', 'APIController@set_home_active')->name('api.set.home_active');
        Route::post('fetch/news/paginate', 'APIController@fetchNewsPaginate')->name('api.news.paginate');
        Route::post('fetch-explore-boats', 'APIController@fetch_explore_boats');
        Route::get('all-boats/nav-description', 'APIController@fetch_nav_description');
    });
    
    /* ----- Start Middleware ----- */
    Route::middleware('auth.admin')->group(
        function () {
            Route::prefix('manage')->group(
                function () {
                    Route::resource('news-asia', 'NewsAsiaController');
                    Route::resource('profile', 'ProfileController');
                    Route::post('password_update/{id}', 'ProfileController@password_update')->name('admin.password.update');
                    Route::resource('language', 'LanguageController');
                    Route::resource('boats', 'BoatController');
                    Route::resource('dealers', 'DealerController');
                    
                    Route::prefix('content')->group(
                        function () {
                            Route::get('/', 'ContentController@main')->name('manage.content.index');
                            Route::get('panel/{country_id}', 'ContentController@panel')->name('manage.content.panel');
                            Route::post('about_malibu/{country_id}', 'ContentController@post_about_malibu')->name('manage.content.about_malibu');
                            Route::post('lang/{country_id}/{tag}', 'ContentController@post_lang')->name('manage.content.lang');
                            Route::resource('explore_boat', 'ExploreBoatController')->names([
                                'index' => 'manage.content.explore_boat.index',
                                'edit' => 'manage.content.explore_boat.edit',
                                'update' => 'manage.content.explore_boat.update',
                                'destroy' => 'manage.content.explore_boat.destroy',
                            ]);
                        }
                    );
                    
                    Route::prefix('dealer')->group( // url : /manage/dealer/...
                        function () {
                            Route::prefix('profile')->group( // url : /manage/dealer/profile
                                function () {
                                    Route::name('manage.dealer.profile.')->group(function () { // route name
                                        // url : /manage/dealer/profile/{dealer_id}
                                        Route::get('{dealer_id}', 'ManageDealerController@getProfile')->name('get');
                                        Route::post('/', 'ManageDealerController@postProfile')->name('post');
                                    });
                                }
                            );
                            
                            Route::prefix('google_maps')->group( // url : /manage/dealer/google_maps
                                function () {
                                    Route::name('manage.dealer.google_maps.')->group(function () { // route name
                                        // url : /manage/dealer/google_maps/{id}
                                        Route::get('/', 'ManageDealerController@getGoogleMaps')->name('get');
                                        Route::post('{id}', 'ManageDealerController@postGoogleMaps')->name('post');
                                    });
                                }
                            );
                            
                            Route::prefix('news')->group( // url : /manage/dealer/news
                                function () {
                                    Route::name('manage.dealer.news.')->group(function () { // route name
                                        // url : /manage/dealer/news/...
                                        Route::get('/index/{dealer_id}', 'ManageDealerController@getNews')->name('index');
                                        Route::get('/create', 'ManageDealerController@getNewsCreate')->name('create');
                                        Route::get('/edit/{id}', 'ManageDealerController@getNewsEdit')->name('edit');
                                        
                                        //									/* POST, PUT, DELETE */
                                        Route::post('/store', 'ManageDealerController@postNewsStore')->name('store');
                                        Route::put('/edit/{id}', 'ManageDealerController@postNewsUpdate')->name('update');
                                        Route::delete('/destroy/{id}', 'ManageDealerController@postNewsDestroy')->name('destroy');
                                        
                                        /* Send request to admin */
                                        Route::post('/request/create/{id}', 'ManageDealerController@postRequestNewsCreate')->name('request.create');
                                        Route::post('/request/update/{id}', 'ManageDealerController@postRequestNewsUpdate')->name('request.update');
                                        Route::post('/request/remove/{id}', 'ManageDealerController@postRequestNewsRemove')->name('request.remove');
                                    });
                                }
                            );
                            
                            Route::prefix('inventory')->group( // url : /manage/dealer/inventory
                                function () {
                                    Route::name('manage.dealer.inventory.')->group(function () { // route name
                                        // url : /manage/dealer/inventory/...
                                        Route::get('/index/{dealer_id}', 'ManageDealerController@getInventory')->name('index');
                                        Route::get('/create', 'ManageDealerController@getInventoryCreate')->name('create');
                                        Route::get('/edit/{id}', 'ManageDealerController@getInventoryEdit')->name('edit');
                                        
                                        /* POST, PUT, DELETE Inventory */
                                        Route::post('/store', 'ManageDealerController@postInventoryStore')->name('store');
                                        Route::put('/edit/{id}', 'ManageDealerController@postInventoryUpdate')->name('update');
                                        Route::delete('/destroy/{id}', 'ManageDealerController@postInventoryDestroy')->name('destroy');
                                    });
                                }
                            );
                        }
                    );
                }
            );
            

app/Models/Dealers.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Dealers extends Model
{
    protected $table = 'dealers';
    
    protected $guarded = [];

    protected $hidden = [
        'password',
        'remember_token'
    ];

    public function getEmailAttribute()
    {
        $email = '-';

        if (!empty($this->attributes['email']) > 0) {
            $email = $this->attributes['email'];
        }

        return $email;
    }

    public function country()
    {
        return $this->belongsTo('App\Models\Countries', 'country_id');
    }

    public function profile()
    {
        return $this->hasOne('App\Models\DealerProfile', 'id');
    }
}

app/Http/Controllers/DealerController.php
<?php

/* ===== Explain this file =====
This file use for manage dealer by admin only.
===== End Explain ===== */

namespace App\Http\Controllers;

use App\Models\Dealers;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class DealerController extends Controller
{
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $dealers = Dealers::all();
        
        return view('back-end.dealers.index', compact('dealers'));
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('back-end.dealers.create');
    }
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Dealers::create($request->except('_token'));
        
        return redirect()
            ->route('dealers.index')
            ->with('update_status', true);
    }
    
    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Dealers $dealer
     *
     * @return \Illuminate\Http\Response
     */
    public function show(Dealers $dealer)
    {
        //
    }
    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Dealers $dealer
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(Dealers $dealer)
    {
        return view('back-end.dealers.edit', compact('dealer'));
    }
    
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\Dealers      $dealer
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Dealers $dealer)
    {
        $username = $request->username;
        $password = $request->password;
        $email    = $request->email;
        
        if ($password) {
            $this->validate(
                $request, [
                    'username' => [
                        'required',
                        'min:4',
                        Rule::unique('dealers')->ignore($dealer->id),
                    ],
                    'password' => 'required|min:6|confirmed',
                ]
            );
            
            $dealer->update(
                [
                    'username' => $username,
                    'password' => bcrypt($password),
                    'email'    => $email,
                ]
            );
        } else {
            $this->validate(
                $request, [
                    'username' => [
                        'required',
                        'min:4',
                        Rule::unique('dealers')->ignore($dealer->id),
                    ],
                ]
            );
    
            $dealer->update(
                [
                    'username' => $username,
                    'email'    => $email,
                ]
            );
        }
        
        return redirect()
            ->route('dealers.index')
            ->with('update_status', true);
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Dealers $dealer
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy(Dealers $dealer)
    {
        //
    }
}

resources/views/back-end/new_design/dealer/account_setting.blade.php
@extends ('layouts.new_design.dealer.app')
@section('content')
    <div class="init-content container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">My account</h3>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <h6 class="heading-small text-muted mb-4">User information</h6>
                        <div class="pl-lg-4">
                            <form action="{{ route('dealer.post_account_setting') }}"
                                  method="post">
                                @if(\Session::has('user_information'))
                                    <div class="form-group">
                                        <div class="alert alert-success" role="alert">
                                            <strong>{{ txt_success() }}</strong>
                                        </div>
                                    </div>
                                    @push ('scripts')
                                        <script>
                                            timeOutAlert('.alert');
                                        </script>
                                    @endpush
                                @endif
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="form-control-label" for="input-username">Username</label>
                                            <input type="text"
                                                   id="input-username"
                                                   class="form-control form-control-alternative"
                                                   placeholder="Username"
                                                   value="{{ dealer()->username }}"
                                                   disabled>
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="form-control-label" for="input-email">Email address</label>
                                            <input type="email"
                                                   id="input-email"
                                                   class="form-control form-control-alternative"
                                                   name="email"
                                                   placeholder="jesse@example.com"
                                                   value="{{ dealer()->email }}">
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div class="form-group text-right">
                                            <button type="submit" class="btn btn-success">Save</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <hr class="my-4"/>
                        <h6 class="heading-small text-muted mb-4">Change Password</h6>
                        <div class="pl-lg-4">
                            <form action="{{ route('dealer.password.update', ['id' => permission_allow()->id]) }}"
                                  method="post">
                                <input type="hidden" name="id" value="{{ permission_allow()->id }}">
                                @if(\Session::has('password_update'))
                                    <div class="form-group">
                                        <div class="alert alert-success" role="alert">
                                            <strong>{{ txt_success() }}</strong>
                                        </div>
                                    </div>
                                    @push ('scripts')
                                        <script>
                                            timeOutAlert('.alert');
                                        </script>
                                    @endpush
                                @endif

                                @if (session()->has('password_status'))
                                    @if (session('password_status') === 'not match')
                                        <div class="form-group">
                                            <div class="alert alert-danger" role="alert">
                                                <strong>Please check password again.</strong>
                                            </div>
                                        </div>
                                        @push ('scripts')
                                            <script>
                                                timeOutAlert('.alert');
                                            </script>
                                        @endpush
                                    @endif
                                @endif
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="form-control-label" for="input-password">New Password</label>
                                            <input type="password"
                                                   id="input-password"
                                                   class="form-control form-control-alternative"
                                                   name="password"
                                                   minlength="6"
                                                   placeholder=""
                                                   value=""
                                                   required>
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="form-control-label" for="input-confirm-password">Confirm
                                                Password</label>
                                            <input type="password"
                                                   id="input-confirm-password"
                                                   class="form-control form-control-alternative"
                                                   name="password_confirmation"
                                                   minlength="6"
                                                   placeholder=""
                                                   value=""
                                                   required>
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div class="form-group text-right">
                                            <button type="submit" class="btn btn-success">Save</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
@endsection

resources/views/back-end/new_design/dealer/profile.blade.php
@extends ('layouts.new_design.dealer.app')
@section ('content')

    <div class="init-content container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0 text-center">
                        <h1>Dealer Profile</h1>
                        <h2>
                            Country : {{ dealerCountry()->display }}
                            &ensp;
                            <img src="{{ dealerCountry()->icon }}" alt="" style="width: 32px; height: 32px;">
                        </h2>
                    </div>
                    <div class="card-body">

                        <form action="{{ route('dealer.profile.update') }}" method="post" enctype="multipart/form-data">
                            <div class="form-group text-right">
                                <h2 class="text-success">Dealer’s details</h2>
                            </div>
                            <div class="form-group">
                                <label for="">Dealer Name (Eng)</label>
                                <input type="text" name="name_en" value="{{ $dealer_profile->name_en }}"
                                       class="form-control" required>
                            </div>
                            @if (checkLangSwitch())
                                <div class="form-group">
                                    <label for="">Dealer Name (Local)</label>
                                    <input type="text" name="name_local" value="{{ $dealer_profile->name_local }}"
                                           class="form-control" required>
                                </div>
                            @endif
                            <div class="form-group">
                                <label for="">Address (Eng)</label>
                                <input type="text" name="address_en" value="{{ $dealer_profile->address_en }}"
                                       class="form-control" required>
                            </div>
                            @if (checkLangSwitch())
                                <div class="form-group">
                                    <label for="">Address (Local)</label>
                                    <input type="text" name="address_local" value="{{ $dealer_profile->address_local }}"
                                           class="form-control" required>
                                </div>
                            @endif
                            <div class="form-group">
                                <label for="">Telephone</label>
                                <input type="text" name="telephone" value="{{ $dealer_profile->telephone }}"
                                       class="form-control" required>
                            </div>
                            <div class="form-group">
                                <label for="">Email</label>
                                <input type="text" name="email" value="{{ $dealer_profile->email }}"
                                       class="form-control" required>
                            </div>
                            <hr>

                            <div class="form-group text-right">
                                <h2 class="text-success">About Dealer</h2>
                            </div>
                            <div class="form-group">
                                <label for="">About Dealer, short Description (Eng)</label>
                                <input type="text" name="short_description_en"
                                       value="{{ $dealer_profile->short_description_en }}" class="form-control"
                                       required>
                            </div>
                            <div class="form-group">
                                <label for="">About Dealer, long Description (Eng)</label>
                                <textarea name="long_description_en" class="form-control"
                                          rows="8" required>{{ $dealer_profile->long_description_en }}</textarea>
                            </div>
                            @if (checkLangSwitch())
                                <div class="form-group">
                                    <label for="">About Dealer, short Description (Local)</label>
                                    <input type="text" name="short_description_local"
                                           value="{{ $dealer_profile->short_description_local }}" class="form-control"
                                           required>
                                </div>
                                <div class="form-group">
                                    <label for="">About Dealer, long Description (Local)</label>
                                    <textarea name="long_description_local" class="form-control"
                                              rows="8" required>{{ $dealer_profile->long_description_local }}</textarea>
                                </div>
                            @endif
                            <div class="form-group">
                                <label for="">Dealer photo</label>
                                <div
                                    style="background-image: url({{ asset('app/'.$dealer_profile->dealer_photo) }}); width: 250px; height: 250px; background-size: contain; background-repeat: no-repeat;"></div>
                                <input type="file" name="dealer_photo" class="form-control-file">
                            </div>
                            <hr>

                            <div class="form-group text-right">
                                <h2 class="text-success">Dealer’s external pages link</h2>
                            </div>
                            <div class="form-group">
                                <label for="">Facebook Link</label>
                                <input type="text" name="facebook_link" value="{{ $dealer_profile->facebook_link }}"
                                       class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="">Instagram Link</label>
                                <input type="text" name="instagram_link" value="{{ $dealer_profile->instagram_link }}"
                                       class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="">Website Link</label>
                                <input type="text" name="website_link" value="{{ $dealer_profile->website_link }}"
                                       class="form-control">
                            </div>
                            <div class="form-group text-right">
                                <button type="submit" class="btn btn-success">Save</button>
                            </div>
                        </form>

                        <hr>

                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection