routes/web.php
<?php
Route::get('/', 'HomeController@home')->name('home');

$client_route = false;
foreach (\App\Models\Countries::all() as $country) {
    $path = explode('/', \Request::path());
    if (strtolower(str_replace(' ', '-', $country->country_name)) === $path[0]) {
        $client_route = true;
    }
}

if (auth()->check() || auth()->guard('dealer')->check()) {
    return redirect('/admin');
} else {
    if ($client_route) {
        /* ----- Switch Language ----- */
        Route::get('{country_name}/set/lang/en', 'HomeController@setLangEn');
        Route::get('{country_name}/set/lang/local', 'HomeController@setLangLocal');
        
        /* ----- Countries ----- */
        Route::get('/{country_name}', 'HomeController@home');
        Route::get('/{country_name}/news', 'HomeController@news')->name('news');
        Route::get('/{country_name}/news/{id}', 'HomeController@news_detail')->name('news_detail');
        Route::get('/{country_name}/boat/{boat_model}', 'HomeController@boat_detail');
        Route::get('/{country_name}/about-malibu', 'HomeController@only_malibu')->name('about-malibu');
        Route::get('/{country_name}/find-a-dealer', 'HomeController@find_dealer')->name('find-dealer');
        Route::get('/{country_name}/contact-dealer', 'HomeController@contact_dealer')->name('contact-dealer');
        Route::get('/{country_name}/all-boats', 'HomeController@all_boats')->name('all-boats');
        Route::get('/{country_name}/inventory', 'HomeController@inventory')->name('inventory');
        Route::get('/{country_name}/inventory/{id}', 'HomeController@inventory_detail')->name('inventory_detail');
    }
    
    /* ----- Login for admin or dealer ----- */
    Route::get('admin', 'BackEndController@login')->name('login');
    Route::post('login', 'BackEndController@post_login')->name('post.login');
    
    /* ----- Contact Dealer ----- */
    Route::post('/session/contact-dealer/store', 'HomeController@session_contact_dealer_store')->name('session.contact-dealer.store');
    
    /* ----- TinyMCE ----- */
    Route::post('tinymce/news/upload', 'TinyMCEController@post_news_upload');
    
    /* ----- Send Mail ----- */
    Route::prefix('mail/send')->group(function () {
        Route::post('contact-us', 'SendMailController@postContactUs')->name('mail.send.contact-us');
        Route::prefix('contact-dealer')->group(function () {
            Route::post('free-test-drive', 'SendMailController@postContactDealerFreeTestDrive')->name('mail.send.contact-dealer.free-test-drive');
            Route::post('request-catalog', 'SendMailController@postContactDealerRequestCatalog')->name('mail.send.contact-dealer.request-catalog');
            Route::post('general', 'SendMailController@postContactDealerGeneral')->name('mail.send.contact-dealer.general');
            Route::post('inventory', 'SendMailController@postContactDealerInventory')->name('mail.send.contact-dealer.inventory');
        });
    });
    
    /* ----- API ----- */
    Route::prefix('api')->group(function () {
        Route::post('set/home_active', 'APIController@set_home_active')->name('api.set.home_active');
        Route::post('fetch/news/paginate', 'APIController@fetchNewsPaginate')->name('api.news.paginate');
        Route::post('fetch-explore-boats', 'APIController@fetch_explore_boats');
        Route::get('all-boats/nav-description', 'APIController@fetch_nav_description');
    });
    
    /* ----- Start Middleware ----- */
    Route::middleware('auth.admin')->group(
        function () {
            Route::prefix('manage')->group(
                function () {
                    Route::resource('news-asia', 'NewsAsiaController');
                    Route::resource('profile', 'ProfileController');
                    Route::post('password_update/{id}', 'ProfileController@password_update')->name('admin.password.update');
                    Route::resource('language', 'LanguageController');
                    Route::resource('boats', 'BoatController');
                    Route::resource('dealers', 'DealerController');
                    
                    Route::prefix('content')->group(
                        function () {
                            Route::get('/', 'ContentController@main')->name('manage.content.index');
                            Route::get('panel/{country_id}', 'ContentController@panel')->name('manage.content.panel');
                            Route::post('about_malibu/{country_id}', 'ContentController@post_about_malibu')->name('manage.content.about_malibu');
                            Route::post('lang/{country_id}/{tag}', 'ContentController@post_lang')->name('manage.content.lang');
                            Route::resource('explore_boat', 'ExploreBoatController')->names([
                                'index' => 'manage.content.explore_boat.index',
                                'edit' => 'manage.content.explore_boat.edit',
                                'update' => 'manage.content.explore_boat.update',
                                'destroy' => 'manage.content.explore_boat.destroy',
                            ]);
                        }
                    );
                    
                    Route::prefix('dealer')->group( // url : /manage/dealer/...
                        function () {
                            Route::prefix('profile')->group( // url : /manage/dealer/profile
                                function () {
                                    Route::name('manage.dealer.profile.')->group(function () { // route name
                                        // url : /manage/dealer/profile/{dealer_id}
                                        Route::get('{dealer_id}', 'ManageDealerController@getProfile')->name('get');
                                        Route::post('/', 'ManageDealerController@postProfile')->name('post');
                                    });
                                }
                            );
                            
                            Route::prefix('google_maps')->group( // url : /manage/dealer/google_maps
                                function () {
                                    Route::name('manage.dealer.google_maps.')->group(function () { // route name
                                        // url : /manage/dealer/google_maps/{id}
                                        Route::get('/', 'ManageDealerController@getGoogleMaps')->name('get');
                                        Route::post('{id}', 'ManageDealerController@postGoogleMaps')->name('post');
                                    });
                                }
                            );
                            
                            Route::prefix('news')->group( // url : /manage/dealer/news
                                function () {
                                    Route::name('manage.dealer.news.')->group(function () { // route name
                                        // url : /manage/dealer/news/...
                                        Route::get('/index/{dealer_id}', 'ManageDealerController@getNews')->name('index');
                                        Route::get('/create', 'ManageDealerController@getNewsCreate')->name('create');
                                        Route::get('/edit/{id}', 'ManageDealerController@getNewsEdit')->name('edit');
                                        
                                        //									/* POST, PUT, DELETE */
                                        Route::post('/store', 'ManageDealerController@postNewsStore')->name('store');
                                        Route::put('/edit/{id}', 'ManageDealerController@postNewsUpdate')->name('update');
                                        Route::delete('/destroy/{id}', 'ManageDealerController@postNewsDestroy')->name('destroy');
                                        
                                        /* Send request to admin */
                                        Route::post('/request/create/{id}', 'ManageDealerController@postRequestNewsCreate')->name('request.create');
                                        Route::post('/request/update/{id}', 'ManageDealerController@postRequestNewsUpdate')->name('request.update');
                                        Route::post('/request/remove/{id}', 'ManageDealerController@postRequestNewsRemove')->name('request.remove');
                                    });
                                }
                            );
                            
                            Route::prefix('inventory')->group( // url : /manage/dealer/inventory
                                function () {
                                    Route::name('manage.dealer.inventory.')->group(function () { // route name
                                        // url : /manage/dealer/inventory/...
                                        Route::get('/index/{dealer_id}', 'ManageDealerController@getInventory')->name('index');
                                        Route::get('/create', 'ManageDealerController@getInventoryCreate')->name('create');
                                        Route::get('/edit/{id}', 'ManageDealerController@getInventoryEdit')->name('edit');
                                        
                                        /* POST, PUT, DELETE Inventory */
                                        Route::post('/store', 'ManageDealerController@postInventoryStore')->name('store');
                                        Route::put('/edit/{id}', 'ManageDealerController@postInventoryUpdate')->name('update');
                                        Route::delete('/destroy/{id}', 'ManageDealerController@postInventoryDestroy')->name('destroy');
                                    });
                                }
                            );
                        }
                    );
                }
            );
            

app/Http/Controllers/BackEndController.php
<?php

/* ===== Explain this file =====
This file use for global back-end functions.
===== End Explain ===== */

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class BackEndController extends Controller
{
    
    public function login()
    {
        if (Auth::check()) {
            return redirect()->route('language.index');
        } else {
            if (Auth::guard('dealer')->check()) {
                return redirect()->route('dealer.profile');
            }
        }
        
        return view('back-end.login');
    }
    
    public function post_login(Request $request)
    {
        $credentials = $request->only('username', 'password');
        
        if (Auth::attempt($credentials)) {
            if (Auth::guard('dealer')->check()) {
                Auth::guard('dealer')->logout();
            }
            
            return redirect()->route('language.index');
        } else {
            if (Auth::guard('dealer')->attempt($credentials)) {
                if (Auth::check()) {
                    Auth::logout();
                }
                session(
                    [
                        'accessCountryId' => Auth::guard('dealer')->user()->country_id,
                    ]
                );
                
                return redirect()->route('dealer.profile');
            }
        }
        
        return redirect()->back()->with('errors', txt_errors('try_again'));
    }
    
    public function logout()
    {
        Auth::logout();
        
        return redirect('/admin');
    }
    
    public function dealer_logout()
    {
        Auth::guard('dealer')->logout();
        
        return redirect('/admin');
    }
}

app/Http/Controllers/LanguageController.php
<?php

/* ===== Explain this file =====
This file use for manage language by admin only.
===== End Explain ===== */

namespace App\Http\Controllers;

use App\Models\AboutMalibu;
use App\Models\Countries;
use App\Models\DealerProfile;
use App\Models\Dealers;
use App\Models\ExploreBoats;
use App\Models\GoogleMaps;
use App\Models\Inventories;
use App\Models\Langs;
use App\Models\News;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

class LanguageController extends Controller
{
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $multiple_status = false;
        
        if (Auth::check()) {
            $countries       = Countries::all();
            $multiple_status = true;
        } else {
            $country_id = permission_allow()->country_id;
            $countries  = Countries::find($country_id);
        }
        
        return view(
            'back-end.language.index', compact('countries', 'multiple_status')
        );
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('back-end.language.create');
    }
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $country_name = $request->country_name;
        $display      = $request->display;
        $icon         = $request->icon;
        $short_name   = $request->short_name;
        $lang_switch  = $request->lang_switch;
        $username     = $request->username;
        $email        = $request->email;
        $password     = $request->password;
        
        $this->validate(
            $request, [
                'username' => 'required|min:4|unique:dealers,username',
                'email'    => 'required|unique:dealers,email',
                'password' => 'required|min:6|confirmed',
            ]
        );
        
        $country = createCountry(
            $country_name, $display, $icon, $short_name, $lang_switch
        );
        $dealer  = createDealer($country->id, $username, $password, $email);
        createDealerProfile($dealer->id);
        createAboutMalibu($country->id);
        createExploreBoat($country->id);
        createGoogleMaps($country->id);
        CreateLangs($country->id);
        createExploreBoat($country->id);
        
        return redirect()->route(
            'access.manage.dealer.profile', ['dealer_id' => $dealer->id]
        );
        
        //return redirect()->route('language.index')->with('insert_status', true);
    }
    
    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }
    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $country = Countries::find($id);
        
        return view('back-end.language.edit', compact('country'));
    }
    
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int                      $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Countries::find($id)->update($request->except('_token', '_method'));
        
        return redirect()->back()->with('language_update', true);
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        AboutMalibu::where('country_id', $id)->delete();
        Countries::destroy($id);
        $dealer    = Dealers::where('country_id', $id)->first();
        $dealer_id = $dealer->id;
        $dealer->delete();
        DealerProfile::where('dealer_id', $dealer_id)->delete();
        ExploreBoats::where('country_id', $id)->delete();
        GoogleMaps::where('country_id', $id)->delete();
        Inventories::where('dealer_id', $dealer_id)->delete();
        Langs::where('country_id', $id)->delete();
        News::where('country_id', $id)->delete();
    }
}

resources/views/back-end/language/create.blade.php
@extends('layouts.admin_app')
@section('content')
    <div class="init-content container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">
                                    <a href="{{ route('language.index') }}">
                                        Language
                                    </a>
                                    / Create
                                </h3>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">

                        <div class="pl-lg-4">
                            <form action="{{ route('language.store') }}" method="post">

                                @if (count($errors->all()))
                                    <div class="form-group">
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li class="text-danger">{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                @endif

                                <div class="row">

                                    <div class="col-lg-12">
                                        <h6 class="heading-small text-muted mb-4">Create Language</h6>
                                    </div>

                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="form-control-label" for="input-country-name">Country
                                                name</label>
                                            <input type="text"
                                                   id="input-country-name"
                                                   class="form-control form-control-alternative"
                                                   name="country_name"
                                                   placeholder="Country name"
                                                   value="{{ old('country_name') }}"
                                                   required>
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="form-control-label" for="input-display">Display</label>
                                            <input type="text"
                                                   id="input-display"
                                                   class="form-control form-control-alternative"
                                                   name="display"
                                                   placeholder="Display"
                                                   value="{{ old('display') }}"
                                                   required>
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="form-control-label" for="input-short-name">Short name example
                                                EN, JP, HK</label>
                                            <input type="text"
                                                   id="input-short-name"
                                                   class="form-control form-control-alternative"
                                                   name="short_name"
                                                   placeholder="Short name">
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="form-control-label" for="input-icon">Icon</label>&ensp;
                                            <input type="text"
                                                   id="input-icon"
                                                   class="form-control form-control-alternative"
                                                   name="icon"
                                                   placeholder="Display"
                                                   value="{{ old('icon') }}"
                                                   required>
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="form-control-label" for="lang-switch">Switch Language</label>
                                            <br>
                                            <input type="radio" name="lang_switch" value="1" checked> Local or English&ensp;
                                            <input type="radio" name="lang_switch" value="0" id="lang-switch"> English
                                            only
                                        </div>
                                    </div>

                                    <div class="col-lg-12">
                                        <hr>
                                    </div>

                                    <div class="col-lg-12">
                                        <h6 class="heading-small text-muted mb-4">Dealer Account</h6>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="form-control-label" for="username">Username</label>&ensp;
                                            <input type="text"
                                                   id="username"
                                                   class="form-control form-control-alternative"
                                                   name="username"
                                                   placeholder="Username"
                                                   minlength="4"
                                                   value="{{ old('username') }}" required>
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="form-control-label" for="email">Email</label>&ensp;
                                            <input type="email"
                                                   id="email"
                                                   class="form-control form-control-alternative"
                                                   name="email"
                                                   placeholder="Email"
                                                   value="{{ old('email') }}" required>
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="form-control-label" for="password">Password</label>&ensp;
                                            <input type="password"
                                                   id="password"
                                                   class="form-control form-control-alternative"
                                                   name="password"
                                                   placeholder="Password"
                                                   minlength="6"
                                                   value="" required>
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="form-control-label" for="password-confirmation">Confirm
                                                Password</label>&ensp;
                                            <input type="password"
                                                   id="password-confirmation"
                                                   class="form-control form-control-alternative"
                                                   name="password_confirmation"
                                                   placeholder="Confirm Password"
                                                   minlength="6"
                                                   value="" required>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-group text-right">
                                            <button type="submit" class="btn btn-success">Create</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
@endsection